version: '3.7'

services:  
  sql.data:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"

  basket.data:
    image: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

