version: '3.7'

services:
  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5432;Database=CapacitacionMicroservicios.IdentityDb;User Id=postgres;Password=pass;
      - LocationApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5109
      - MarketingApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5110
      - BasketApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5103
      - OrderingApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5102
      - MobileShoppingAggClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5120
      - WebShoppingAggClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5121
    ports:
      - "5105:80"   

  catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5432;Database=CapacitacionMicroservicios.CatalogDb;User Id=postgres;Password=pass;
      - PicBaseUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5202/api/v1/catalog/items/[0]/pic/
      - EventBusConnection=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5672
      - EventBusUserName=guest
      - EventBusPassword=guest        
      - UseCustomizationData=True
    ports:
      - "5101:80"

  basket:
    #build:
    #  dockerfile: Dockerfile-debug
    #  target: debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - SqlConnectionString=Server=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5432;Database=CapacitacionMicroservicios.BasketDb;User Id=sa;Password=Pass@word
      - ConnectionString=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:6379
      - identityUrl=http://identity.api              #Local: You need to open your local dev-machine firewall at range 5100-5110.
      - IdentityUrlExternal=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105
      - EventBusConnection=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5672
      - EventBusUserName=guest
      - EventBusPassword=guest
    ports:
      - "5103:80"

  ordering:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=Server=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5432;Database=CapacitacionMicroservicios.OrderingDb;User Id=postgres;Password=pass;
      - EventBusConnection=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5672
      - EventBusUserName=guest
      - EventBusPassword=guest  
      - EVENTSTORE_URL=tcp://admin:changeit@eventstore:1113
    ports:
      - "5104:80"

  webshoppingagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - urls__basket=http://basket.api
      - urls__catalog=http://catalog.api
      - urls__orders=http://ordering.api
      - urls__identity=http://identity.api              #Local: You need to open your local dev-machine firewall at range 5100-5110.
    ports:
      - "5121:80"   # Important: In a production environment your should remove the external port (5121) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80).
  
  webshoppingapigw:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identity.api              #Local: You need to open your local dev-machine firewall at range 5100-5110.
    ports:
      - "5202:80"   
    volumes:
      - ./src/ApiGateways/Web.Bff.Shopping/apigw:${ESHOP_OCELOT_VOLUME_SPEC:-/app/configuration}

  payment:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - EventBusConnection=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5672
      - EventBusUserName=guest
      - EventBusPassword=guest  
    ports:
      - "5108:80"   # Important: In a production environment your should remove the external port (5108) kept here for microservice debugging purposes. 
                    # The API Gateway redirects and access through the internal port (80).
  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PurchaseUrl=http://webshoppingapigw
      - IdentityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105  # Local Mac: Use http://docker.for.mac.localhost:5105 || Local Windows:  Use 10.0.75.1 in a "Docker for Windows" environment, if using "localhost" from browser. || #Remote access: Use ${ESHOP_EXTERNAL_DNS_NAME_OR_IP} if using external IP or DNS name from browser.
      - MarketingUrl=http://webmarketingapigw                                                    
      - CatalogUrlHC=http://catalog.api/hc
      - OrderingUrlHC=http://ordering.api/hc
      - IdentityUrlHC=http://identity.api/hc     #Local: Use ${ESHOP_PROD_EXTERNAL_DNS_NAME_OR_IP}, if using external IP or DNS name from browser.          
      - BasketUrlHC=http://basket.api/hc
      - MarketingUrlHC=http://marketing.api/hc
      - PaymentUrlHC=http://payment.api/hc
      - SignalrHubUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5202
      - UseCustomizationData=True
      - ApplicationInsights__InstrumentationKey=${INSTRUMENTATION_KEY}
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "5100:80"

  signalrhub:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80     
      - AzureServiceBusEnabled=False
      - OrchestratorType=${ORCHESTRATOR_TYPE}
      - identityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5105              #Local: You need to open your local dev-machine firewall at range 5100-5110.
      - EventBusConnection=${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:5672
    ports:
      - "5112:80"